### ISSUE TITLE
After downloading .dll file and following instructions, I've noticed that I don't have "gluasteal" file at all.

### ISSUE THREAD

**Issue by JustReg2Download** [lewisclark/glua-steal#20]
I am so f*cking angry that I do third try to play with cheats in a row, and I am getting random issues again.
As I undestand, "/username/" means your nickname in OS (my name is user).
https://youtu.be/tP2ZWv09898

**Comment by lewisclark** [comment]
Can you give all the information you can?

- Is the game crashing when you inject? 
- Are you using the 32-bit or 64-bit version of the game?
- Are you using the correct version of glua-steal to match the version of the game (32-bit/64-bit)?
- What are you using to inject glua-steal?
- Which version of glua-steal are you using?

**Comment by JustReg2Download** [comment]
I didn't meet any crashes during injecting.
I didn't find the way how to see game's version (but my OS is 64bit).
Latest version and 64 bit.
Process Hacker 2
Gluasteal v1.9 .

**Comment by JustReg2Download** [comment]
Shall I speak with you at any social platform?
I'd like to show you up my screen with discord because I really want to solve it.

**Comment by lewisclark** [comment]
Try this first:
- Exit the game
- Right click on Garry's Mod in Steam and select Properties
- Go to the Betas tab
- Select the 'x86_64 - Chromium + 64-bit binaries' branch
- Let the game update and then try to inject the 64-bit dll again

If that still doesn't work, feel free to contact me on Discord: lewis#5404.

**Comment by JustReg2Download** [comment]
And watch if file appeared?

**Comment by JustReg2Download** [comment]
What if I have only "log" folder inside?

**Comment by JustReg2Download** [comment]
![фыввфывфвы](https://user-images.githubusercontent.com/72761693/95893776-cf577880-0d90-11eb-9169-45ac86af3ca9.PNG)
I am sorry for question which might look dumb, but where should I put my lua file?
Here?

**Comment by lewisclark** [comment]
https://github.com/lewisclark/glua-steal#lua-loader-load-before-autorun
Create a file called gluasteal.lua in your gluasteal directory, where the log file is.

**Comment by JustReg2Download** [comment]
![апврвапвапваппавпавпвапва](https://user-images.githubusercontent.com/72761693/95895029-b0f27c80-0d92-11eb-9fc0-d1c8082058be.PNG)
![лдяляляляляляя](https://user-images.githubusercontent.com/72761693/95895032-b18b1300-0d92-11eb-8431-8b4ab29c60d0.PNG)
This one?

**Comment by lewisclark** [comment]
No. Create a **file**, not a folder called gluasteal.lua in your gluasteal directory, where the log file is. Put all of the Lua code you want to run in gluasteal.lua.

**Comment by JustReg2Download** [comment]
Will it work if I rename cheat lua file in "gluasteal.lua"?
![asdasdasdasdasdasdasdasdasda](https://user-images.githubusercontent.com/72761693/95896584-1fd0d500-0d95-11eb-9250-8dfb74d789e3.PNG)

**Comment by lewisclark** [comment]
Yes. That is the only file that is loaded.

**Comment by JustReg2Download** [comment]
Thanks, it works.
Hope I will not have surprises like viruses from DLL, however I hope that I picked right man.

**Comment by JustReg2Download** [comment]
Last question.
Can this dll bypass server's anticheat?

**Comment by lewisclark** [comment]
You can always compile the dll from source code if you're worried. No, any trivial anti-cheat can detect this. However, it is possible to write an anti-cheat bypass in the gluasteal.lua file because it loads before the anti-cheat does.

**Comment by JustReg2Download** [comment]
Also I found a bug, that dll loads cheat to many times and it forces cheat to open a lot of client settings windows.
Could you help me?
Also loader is great, but my soul is still worried about no to get ban on your favorite server.

**Comment by x4fx77x4f** [comment]
> Also I found a bug, that dll loads cheat to many times and it forces cheat to open a lot of client settings windows.

This is because the `gluasteal.lua` file is run every single time any Lua code is executed.

Using the `gluasteal` global functions documented in `README.md`, you could check that the current file is `includes/init.lua`, which is the first file that will be executed when you join a server [according to this article on the Garry's Mod Wiki](https://wiki.facepunch.com/gmod/Lua_Loading_Order).

You could also abort if a certain global variable exists, and then create it once you've loaded. **Keep in mind that any anti-cheats on the server will be able to detect the foreign global variable,** and also that the environment your script will run in is recreated every time it's run, so you'll need to use `_G` to do it that way.

You should really only be using glua-steal if you are familiar with Lua, but since I feel like being nice:
```lua
if gluasteal.SCRIPT == "includes/init.lua" then
    -- your code here
end
```
I haven't tested this, but it should work.

> Also loader is great, but my soul is still worried about no to get ban on my favorite server.

If it's your favorite server, don't cheat on it. glua-steal is easily detectable by default (if you are using the Lua loader), it's only made undetectable if *your code* is able to hide itself from the anti-cheat. Even if your cheat is undetectable, *why* would you want to cheat on your favorite server? I totally understand the interest in cheating, but it might be your downfall.

**Comment by JustReg2Download** [comment]
Thank you!
Does anticheat detects dll cheats (I think they are different)?
Could DLL cheats "hide" you from anticheat?
I don't think that anticheat can see non lua based cheats.

**Comment by x4fx77x4f** [comment]
> I am bad at lua because I am new here.

By chance, Lua is a good choice for a first programming language to learn. Lua is simple in comparison to other languages, and Lua scripts vaguely resemble plain English due to the use of keywords instead of, say, braces.

> Is "-- your code here" means my cheat name (i renamed my cheat in gluasteal.lua)?

I'm not sure if "cheat name" is supposed to refer to the cheat's code or literally its name.
https://en.wiktionary.org/wiki/name#Noun
https://ru.wiktionary.org/wiki/name#Значение

Put your *code* there. Either put everything in your cheat file there, or use `gluasteal.include` to run it that way. Again, **you should really know Lua before using a tool like this**, but since my patience hasn't run out for today:
If your cheat is in `gluasteal.lua`, then put `if gluasteal.SCRIPT == "includes/init.lua" then` at the very top before everything else, and `end` at the end after everything else.
If your cheat file is in some other file (for example: `example_filename.lua`), your `gluasteal.lua` file should look like this:
```lua
if gluasteal.SCRIPT == "includes/init.lua" then
    gluasteal.include("example_filename.lua")
end
```

> Does anticheat detects dll cheats (I think they are different)?

If you don't use the Lua injection feature of glua-steal, glua-steal is undetectable (as far as I know). If you *do* use the Lua injection feature, **it is detectable unless the cheat has code specifically to prevent detection**.

> Could DLL cheats "hide" you from anticheat?

An external tool like this *could* do all of the hard work of making your Lua code undetectable for you, but **this particular tool does not.**
