### ISSUE TITLE
Not able to compile on Linux

### ISSUE THREAD

**Issue by AroPix** [lewisclark/glua-steal#27]
**Describe the bug**
When trying to compile glua-steal for Linux, it fails with several erros. One being that <vector> is not imported and other ones i can't seem to fix myself as i don't understand what these lines of code do. Even tried using older GCC versions.

**Expected behavior**
Compiling would work without problems.

**Screenshots**
![Screenshot_20220709_030606](https://user-images.githubusercontent.com/57004660/178085936-85707add-9137-48ad-b1b5-96df95bb5ebd.png)

**Additional details (please complete the following information):**
 - OS: Linux (Manjaro Arch)
 - glua-steal version and architecture: Newest and both fail

**Comment by x4fx77x4f** [comment]
Looking up "MINSIGSTKSZ" gets me to [this Stack Overflow post from someone also on Manjaro](https://stackoverflow.com/a/71454718); apparently it has to do with [this change in glibc](https://sourceware.org/git/?p=glibc.git;a=blob;f=NEWS;h=85e84fe53699fe9e392edffa993612ce08b2954a;hb=HEAD). The issue is coming from Catch2 code, which this repository includes as a submodule. [Catch2 fixed this issue in 2.13.5](https://github.com/catchorg/Catch2/blob/devel/docs/release-notes.md#2135), but glua-steal uses 2.13.0. It ought to be updated.

**Comment by lewisclark** [comment]
Thank you, both. I've updated Catch2 to v2.13.9 and plan to update to v3 when I have time to resolve the breaking changes.

**Comment by AroPix** [comment]
I was able to copile it without erros, but i can't seem to find the compiled .so file. Is there any way i could contact you through discord as example? And also thanks for the quick response, didn't think that a 2 year old project would still get support by the creator :)

**Comment by AroPix** [comment]
Oh im dumb it is libgluasteal.so right?

**Comment by AroPix** [comment]
Okay nvm i got it working. The only thing i had to fix was adding `#include <vector>` to sanitization.cpp.
